<a href="https://colab.research.google.com/github/AfandiSanch/jnetsurfer/blob/main/Another_copy_of_Fiks_37_baris_ALL_DATASET_Detail_algoritma_Bahan_Skripsi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas numpy scikit-learn xgboost tensorflow keras tabulate


In [ ]:
import pandas as pd

# Memuat dataset
file_path = '/content/drive/MyDrive/Master Data Skripsi/RT_IOT2022 -(37).csv'
# Sesuaikan dengan path file Anda di Google Colab
data = pd.read_csv(file_path, delimiter=';')

# Menampilkan beberapa baris pertama dari dataset
data.head()

id  id.orig_p  id.resp_p proto service  flow_duration  fwd_pkts_tot  \
0   0      38667       1883   tcp    mqtt      32.011598             9   
1   1      51143       1883   tcp    mqtt      31.883584             9   
2   2      44761       1883   tcp    mqtt      32.124053             9   
3   3      60893       1883   tcp    mqtt      31.961063             9   
4   4      51087       1883   tcp    mqtt      31.902362             9   

   bwd_pkts_tot  fwd_data_pkts_tot  bwd_data_pkts_tot  ...  active.std  \
0             5                  3                  3  ...         0.0   
1             5                  3                  3  ...         0.0   
2             5                  3                  3  ...         0.0   
3             5                  3                  3  ...         0.0   
4             5                  3                  3  ...         0.0   

      idle.min     idle.max     idle.tot     idle.avg  idle.std  \
0  29729182.96  29729182.96  29729182.96  29729182.96       0.0   
1  29855277.06  29855277.06  29855277.06  29855277.06       0.0   
2  29842149.02  29842149.02  29842149.02  29842149.02       0.0   
3  29913774.97  29913774.97  29913774.97  29913774.97       0.0   
4  29814704.90  29814704.90  29814704.90  29814704.90       0.0   

   fwd_init_window_size  bwd_init_window_size  fwd_last_window_size  \
0                 64240                 26847                   502   
1                 64240                 26847                   502   
2                 64240                 26847                   502   
3                 64240                 26847                   502   
4                 64240                 26847                   502   

    Attack_type  
0  MQTT_Publish  
1  MQTT_Publish  
2  MQTT_Publish  
3  MQTT_Publish  
4  MQTT_Publish  

[5 rows x 85 columns]

In [ ]:
from tabulate import tabulate

# Memisahkan fitur dan target
X = data.drop('Attack_type', axis=1)
y = data['Attack_type']

# Menampilkan kolom fitur
print("Kolom Fitur:")
feature_columns_df = pd.DataFrame(X.columns, columns=["Kolom Fitur"])
print(tabulate(feature_columns_df.astype(str), headers="keys", tablefmt="pretty"))

Kolom Fitur:
+----+--------------------------+
|    |       Kolom Fitur        |
+----+--------------------------+
| 0  |            id            |
| 1  |        id.orig_p         |
| 2  |        id.resp_p         |
| 3  |          proto           |
| 4  |         service          |
| 5  |      flow_duration       |
| 6  |       fwd_pkts_tot       |
| 7  |       bwd_pkts_tot       |
| 8  |    fwd_data_pkts_tot     |
| 9  |    bwd_data_pkts_tot     |
| 10 |     fwd_pkts_per_sec     |
| 11 |     bwd_pkts_per_sec     |
| 12 |    flow_pkts_per_sec     |
| 13 |      down_up_ratio       |
| 14 |   fwd_header_size_tot    |
| 15 |   fwd_header_size_min    |
| 16 |   fwd_header_size_max    |
| 17 |   bwd_header_size_tot    |
| 18 |   bwd_header_size_min    |
| 19 |   bwd_header_size_max    |
| 20 |   flow_FIN_flag_count    |
| 21 |   flow_SYN_flag_count    |
| 22 |   flow_RST_flag_count    |
| 23 |    fwd_PSH_flag_count    |
| 24 |    bwd_PSH_flag_count    |
| 25 |   flow_ACK_flag_count    |
|

In [ ]:
# Menampilkan target
print("\nTarget:")
target_df = pd.DataFrame(y).astype(str)
print(tabulate(target_df, headers="keys", tablefmt="pretty"))


Target:
+-----+----------------------------+
|     |        Attack_type         |
+-----+----------------------------+
|  0  |        MQTT_Publish        |
|  1  |        MQTT_Publish        |
|  2  |        MQTT_Publish        |
|  3  |        MQTT_Publish        |
|  4  |        MQTT_Publish        |
|  5  |        MQTT_Publish        |
|  6  |        MQTT_Publish        |
|  7  |        MQTT_Publish        |
|  8  |        MQTT_Publish        |
|  9  |        MQTT_Publish        |
| 10  |        MQTT_Publish        |
| 11  |        MQTT_Publish        |
| 12  |        MQTT_Publish        |
| 13  |        MQTT_Publish        |
| 14  |        MQTT_Publish        |
| 15  |        MQTT_Publish        |
| 16  |        MQTT_Publish        |
| 17  |        MQTT_Publish        |
| 18  |        MQTT_Publish        |
| 19  |        MQTT_Publish        |
| 20  |        MQTT_Publish        |
| 21  |        MQTT_Publish        |
| 22  |        MQTT_Publish        |
| 23  |        MQTT_Publish  

In [ ]:
# Menampilkan tipe data setiap kolom
print("\nTipe Data Setiap Kolom:")
dtypes_df = pd.DataFrame(data.dtypes, columns=["Tipe Data"])
print(tabulate(dtypes_df, headers="keys", tablefmt="pretty"))


Tipe Data Setiap Kolom:
+--------------------------+-----------+
|                          | Tipe Data |
+--------------------------+-----------+
|            id            |   int64   |
|        id.orig_p         |   int64   |
|        id.resp_p         |   int64   |
|          proto           |  object   |
|         service          |  object   |
|      flow_duration       |  float64  |
|       fwd_pkts_tot       |   int64   |
|       bwd_pkts_tot       |   int64   |
|    fwd_data_pkts_tot     |   int64   |
|    bwd_data_pkts_tot     |   int64   |
|     fwd_pkts_per_sec     |  float64  |
|     bwd_pkts_per_sec     |  float64  |
|    flow_pkts_per_sec     |  float64  |
|      down_up_ratio       |  float64  |
|   fwd_header_size_tot    |   int64   |
|   fwd_header_size_min    |   int64   |
|   fwd_header_size_max    |   int64   |
|   bwd_header_size_tot    |   int64   |
|   bwd_header_size_min    |   int64   |
|   bwd_header_size_max    |   int64   |
|   flow_FIN_flag_count    |   i

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Menyimpan nilai asli dari kolom 'Attack_type'
original_attack_type = data['Attack_type'].unique()

# Mengubah kolom 'Attack_type' menjadi numerik
label_encoder = LabelEncoder()
encoded_attack_type = label_encoder.fit_transform(data['Attack_type'])

# Mengambil kategori asli dan nilai encoded-nya
categories = label_encoder.classes_
encoded_values = list(range(len(categories)))

# Membuat tabel perbandingan
comparison_table = pd.DataFrame({
    "Sebelum Encode": categories,
    "Setelah Encode": encoded_values
})

# Menampilkan tabel perbandingan
print("Encode Kolom Attack Type")
print(tabulate(comparison_table, headers="keys", tablefmt="pretty"))

Encode Kolom Attack Type
+----+----------------------------+----------------+
|    |       Sebelum Encode       | Setelah Encode |
+----+----------------------------+----------------+
| 0  |       ARP_poisioning       |       0        |
| 1  |       DDOS_Slowloris       |       1        |
| 2  |       DOS_SYN_Hping        |       2        |
| 3  |        MQTT_Publish        |       3        |
| 4  | Metasploit_Brute_Force_SSH |       4        |
| 5  |       NMAP_FIN_SCAN        |       5        |
| 6  |     NMAP_OS_DETECTION      |       6        |
| 7  |       NMAP_TCP_scan        |       7        |
| 8  |       NMAP_UDP_SCAN        |       8        |
| 9  |    NMAP_XMAS_TREE_SCAN     |       9        |
| 10 |        Thing_Speak         |       10       |
| 11 |         Wipro_bulb         |       11       |
+----+----------------------------+----------------+


In [ ]:
# Menyimpan nilai asli dari kolom 'proto'
original_proto = data['proto'].unique()

# Mengubah kolom 'proto' menjadi numerik
label_encoder = LabelEncoder()
encoded_proto = label_encoder.fit_transform(data['proto'])

# Mengambil kategori asli dan nilai encoded-nya
categories = label_encoder.classes_
encoded_values = list(range(len(categories)))
# Membuat tabel perbandingan
comparison_table = pd.DataFrame({
    "Sebelum Encode": categories,
    "Setelah Encode": encoded_values
})
# Menampilkan tabel perbandingan
print("Encode Kolom Proto")
print(tabulate(comparison_table, headers="keys", tablefmt="pretty"))

Encode Kolom Proto
+---+----------------+----------------+
|   | Sebelum Encode | Setelah Encode |
+---+----------------+----------------+
| 0 |      tcp       |       0        |
| 1 |      udp       |       1        |
+---+----------------+----------------+


In [ ]:
from sklearn.preprocessing import LabelEncoder
from tabulate import tabulate


# Menyimpan nilai asli dari kolom 'service'
original_service = data['service'].unique()

# Mengubah kolom 'service' menjadi numerik
label_encoder = LabelEncoder()
encoded_service = label_encoder.fit_transform(data['service'])

# Mengambil kategori asli dan nilai encoded-nya
categories = label_encoder.classes_
encoded_values = list(range(len(categories)))

# Membuat tabel perbandingan
comparison_table = pd.DataFrame({
    "Sebelum Encode": categories,
    "Setelah Encode": encoded_values
})

# Menampilkan tabel perbandingan
print("Encode Kolom Service")
print(tabulate(comparison_table, headers="keys", tablefmt="pretty"))

Encode Kolom Service
+---+----------------+----------------+
|   | Sebelum Encode | Setelah Encode |
+---+----------------+----------------+
| 0 |       -        |       0        |
| 1 |      dns       |       1        |
| 2 |      http      |       2        |
| 3 |      irc       |       3        |
| 4 |      mqtt      |       4        |
| 5 |      ntp       |       5        |
| 6 |      ssh       |       6        |
| 7 |      ssl       |       7        |
+---+----------------+----------------+


In [ ]:
from sklearn.preprocessing import LabelEncoder

# Mengidentifikasi kolom-kolom kategorikal
categorical_columns = data.select_dtypes(include=['object']).columns

# Mengubah kolom-kolom kategorikal menjadi numerik
for column in categorical_columns:
    label_encoder = LabelEncoder()
    data[column] = label_encoder.fit_transform(data[column])

# Menyimpan hasil konversi ke file Excel
data.to_excel('data_encoded.xlsx', index=False)
print("Data yang telah diencode disimpan ke data_encoded.xlsx")

# Memeriksa hasil LabelEncoder untuk 'Attack_type'
print(f"Kelas yang telah di-encode: {label_encoder.classes_}")

Data yang telah diencode disimpan ke data_encoded.xlsx
Kelas yang telah di-encode: ['ARP_poisioning' 'DDOS_Slowloris' 'DOS_SYN_Hping' 'MQTT_Publish'
 'Metasploit_Brute_Force_SSH' 'NMAP_FIN_SCAN' 'NMAP_OS_DETECTION'
 'NMAP_TCP_scan' 'NMAP_UDP_SCAN' 'NMAP_XMAS_TREE_SCAN' 'Thing_Speak'
 'Wipro_bulb']


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tabulate import tabulate

# Mengidentifikasi kolom-kolom kategorikal
categorical_columns = data.select_dtypes(include=['object']).columns

# Mengubah kolom-kolom kategorikal menjadi numerik
for column in categorical_columns:
    label_encoder = LabelEncoder()
    data[column] = label_encoder.fit_transform(data[column])

# Memisahkan fitur dan target
X = data.drop('Attack_type', axis=1)
y = data['Attack_type']

# Membagi data menjadi set pelatihan dan set pengujian secara proporsional untuk setiap kategori
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Menstandarkan fitur
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Mengonversi hasil standarisasi kembali ke DataFrame untuk kemudahan tampilan
X_train_df = pd.DataFrame(X_train, columns=X.columns)
X_test_df = pd.DataFrame(X_test, columns=X.columns)
y_train_df = pd.DataFrame(y_train.reset_index(drop=True), columns=['Attack_type'])
y_test_df = pd.DataFrame(y_test.reset_index(drop=True), columns=['Attack_type'])

# Menampilkan tabel train setelah distandarisasi
print("Tabel Train Setelah Distandarisasi:")
print(tabulate(X_train_df.head(), headers="keys", tablefmt="pretty"))

# Menampilkan tabel test setelah distandarisasi
print("\nTabel Test Setelah Distandarisasi:")
print(tabulate(X_test_df.head(), headers="keys", tablefmt="pretty"))

# Menampilkan target train
print("\nTarget Train:")
print(tabulate(y_train_df.head(), headers="keys", tablefmt="pretty"))

# Menampilkan target test
print("\nTarget Test:")
print(tabulate(y_test_df.head(), headers="keys", tablefmt="pretty"))


Tabel Train Setelah Distandarisasi:
+---+---------------------+----------------------+----------------------+----------------------+---------------------+----------------------+----------------------+----------------------+----------------------+---------------------+----------------------+---------------------+---------------------+--------------------+----------------------+----------------------+---------------------+---------------------+---------------------+---------------------+---------------------+----------------------+---------------------+----------------------+--------------------+----------------------+---------------------+--------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+-----------------------+-----------------------+---------

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tabulate import tabulate

# Melatih model Random Forest
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=0
)

# Train the model
rf_model.fit(X_train, y_train)

# Memprediksi dan mengevaluasi model
y_pred_rf = rf_model.predict(X_test)

# Akurasi model keseluruhan
accuracy = accuracy_score(y_test, y_pred_rf)
accuracy_percentage = accuracy * 100
print(f"Random Forest Accuracy: {accuracy_percentage:.2f}%")


Random Forest Accuracy: 91.60%


In [ ]:

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred_rf)
print("\nConfusion Matrix:")
print(conf_matrix)

# Fungsi untuk menghitung TP, FP, FN, TN dari confusion matrix
def calculate_tp_fp_fn_tn(conf_matrix):
    tp = conf_matrix.diagonal()
    fp = conf_matrix.sum(axis=0) - tp
    fn = conf_matrix.sum(axis=1) - tp
    tn = conf_matrix.sum() - (tp + fp + fn)
    return tp, fp, fn, tn

tp_rf, fp_rf, fn_rf, tn_rf = calculate_tp_fp_fn_tn(conf_matrix)

# Mengonversi TP, FP, FN, TN menjadi DataFrame
tp_df = pd.DataFrame({
    'Category': rf_model.classes_,
    'TP': tp_rf
})

fp_df = pd.DataFrame({
    'Category': rf_model.classes_,
    'FP': fp_rf
})

fn_df = pd.DataFrame({
    'Category': rf_model.classes_,
    'FN': fn_rf
})

tn_df = pd.DataFrame({
    'Category': rf_model.classes_,
    'TN': tn_rf
})

# Menampilkan tabel TP, FP, FN, dan TN
print("\nTrue Positives (TP) per Category:")
print(tabulate(tp_df, headers='keys', tablefmt='pretty'))

print("\nFalse Positives (FP) per Category:")
print(tabulate(fp_df, headers='keys', tablefmt='pretty'))

print("\nFalse Negatives (FN) per Category:")
print(tabulate(fn_df, headers='keys', tablefmt='pretty'))

print("\nTrue Negatives (TN) per Category:")
print(tabulate(tn_df, headers='keys', tablefmt='pretty'))

# Mengubah target names menjadi string
target_names = [str(i) for i in rf_model.classes_]

# Classification report
classification_report_str = classification_report(y_test, y_pred_rf, target_names=target_names)
print("\nClassification Report:")
print(classification_report_str)

# Mengubah classification report menjadi DataFrame
classification_report_dict = classification_report(y_test, y_pred_rf, target_names=target_names, output_dict=True)
classification_report_df = pd.DataFrame(classification_report_dict).transpose()

# Extract akurasi per kategori dari classification report
classification_report_dict = classification_report(y_test, y_pred_rf, target_names=target_names, output_dict=True)
category_accuracy = {category: metrics['recall'] for category, metrics in classification_report_dict.items() if category != 'accuracy'}

# Tampilkan akurasi per kategori
category_accuracy_df = pd.DataFrame(list(category_accuracy.items()), columns=['Category', 'Accuracy'])
category_accuracy_df['Accuracy'] = (category_accuracy_df['Accuracy'] * 100).round(2)  # Convert to percentage and round to 2 decimal places
print("\nAccuracy per Category:")
print(tabulate(category_accuracy_df, headers='keys', tablefmt='pretty'))

# Menyimpan hasil ke Excel dan file teks
results_excel_path = '/content/drive/MyDrive/Hasil Algoritma/Random Forest/random_forest_results.xlsx'
classification_report_excel_path = '/content/drive/MyDrive/Hasil Algoritma/Random Forest/random_forest_classification_report.xlsx'
conf_matrix_excel_path = '/content/drive/MyDrive/Hasil Algoritma/Random Forest/confusion_matrix.xlsx'
category_accuracy_excel_path = '/content/drive/MyDrive/Hasil Algoritma/Random Forest/category_accuracy.xlsx'
tp_excel_path = '/content/drive/MyDrive/Hasil Algoritma/Random Forest/tp.xlsx'
fp_excel_path = '/content/drive/MyDrive/Hasil Algoritma/Random Forest/fp.xlsx'
fn_excel_path = '/content/drive/MyDrive/Hasil Algoritma/Random Forest/fn.xlsx'
tn_excel_path = '/content/drive/MyDrive/Hasil Algoritma/Random Forest/tn.xlsx'

# Simpan hasil prediksi dan evaluasi
results_df = pd.DataFrame({"Actual": y_test.reset_index(drop=True), "Predicted": y_pred_rf})
results_df.to_excel(results_excel_path, index=False)

# Simpan confusion matrix ke Excel
conf_matrix_df = pd.DataFrame(conf_matrix, index=target_names, columns=target_names)
conf_matrix_df.to_excel(conf_matrix_excel_path)

# Simpan classification report ke Excel
classification_report_df.to_excel(classification_report_excel_path, index=True)

# Simpan akurasi per kategori ke Excel
category_accuracy_df.to_excel(category_accuracy_excel_path, index=False)

# Simpan TP, FP, FN, dan TN ke Excel
tp_df.to_excel(tp_excel_path, index=False)
fp_df.to_excel(fp_excel_path, index=False)
fn_df.to_excel(fn_excel_path, index=False)
tn_df.to_excel(tn_excel_path, index=False)

# Cetak informasi path penyimpanan
print(f"\nHasil prediksi Random Forest telah disimpan di: {results_excel_path}")
print(f"Confusion Matrix telah disimpan di: {conf_matrix_excel_path}")
print(f"Classification Report telah disimpan di: {classification_report_excel_path}")
print(f"Accuracy per Category telah disimpan di: {category_accuracy_excel_path}")
print(f"True Positives (TP) telah disimpan di: {tp_excel_path}")
print(f"False Positives (FP) telah disimpan di: {fp_excel_path}")
print(f"False Negatives (FN) telah disimpan di: {fn_excel_path}")
print(f"True Negatives (TN) telah disimpan di: {tn_excel_path}")



Confusion Matrix:
[[ 8  0  0  0  1  0  0  2  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  1  0  0  0]
 [ 0  0 11  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 11  0  0  0  0  0  0  0  0]
 [ 1  0  0  0 10  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  7  0  0  0  2  0  0]
 [ 0  0  0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 12  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  9  0  0  0]
 [ 0  0  0  0  0  1  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0]
 [ 0  0  0  0  1  0  0  0  0  0  0 10]]

True Positives (TP) per Category:
+----+----------+----+
|    | Category | TP |
+----+----------+----+
| 0  |    0     | 8  |
| 1  |    1     | 10 |
| 2  |    2     | 11 |
| 3  |    3     | 11 |
| 4  |    4     | 10 |
| 5  |    5     | 7  |
| 6  |    6     | 11 |
| 7  |    7     | 12 |
| 8  |    8     | 9  |
| 9  |    9     | 10 |
| 10 |    10    | 11 |
| 11 |    11    | 10 |
+----+----------+----+

False Positives (FP) per Category:
+----+----------+----+
|    | Category | FP |
+----+----------+----+
| 0 

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

# Membuat dan melatih model XGBoost
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=0
)

xgb_model.fit(X_train, y_train)

# Memprediksi dan mengevaluasi model
y_pred_xgb = xgb_model.predict(X_test)

# Menghitung akurasi keseluruhan
accuracy = accuracy_score(y_test, y_pred_xgb)
accuracy_percentage = accuracy * 100

# Menampilkan akurasi dalam format persentase
print(f"XGBoost Accuracy: {accuracy_percentage:.2f}%")



XGBoost Accuracy: 92.37%


In [ ]:
# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred_xgb)
print("\nConfusion Matrix:")
print(conf_matrix)

# Menghitung TP, FP, FN, TN untuk setiap kategori
tp = conf_matrix.diagonal()
fp = conf_matrix.sum(axis=0) - tp
fn = conf_matrix.sum(axis=1) - tp
tn = conf_matrix.sum() - (fp + fn + tp)

# Buat DataFrame untuk TP, FP, FN, TN
metrics_df = pd.DataFrame({
    'Category': target_names,
    'True Positive (TP)': tp,
    'False Positive (FP)': fp,
    'False Negative (FN)': fn,
    'True Negative (TN)': tn
})
print("\nTP, FP, FN, TN per Category:")
print(tabulate(metrics_df, headers='keys', tablefmt='pretty'))

# Mengubah target names menjadi string
target_names = [str(i) for i in xgb_model.classes_]

# Classification report
classification_report_dict = classification_report(y_test, y_pred_xgb, target_names=target_names, output_dict=True)
print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb, target_names=target_names))

# Tampilkan akurasi per kategori
category_accuracy = {category: metrics['recall'] for category, metrics in classification_report_dict.items() if category != 'accuracy'}
category_accuracy_df = pd.DataFrame(list(category_accuracy.items()), columns=['Category', 'Accuracy'])
category_accuracy_df['Accuracy'] = (category_accuracy_df['Accuracy'] * 100).round(2)  # Convert to percentage and round to 2 decimal places
print("\nAccuracy per Category:")
print(tabulate(category_accuracy_df, headers='keys', tablefmt='pretty'))

# Menyimpan hasil ke Excel
output_dir = '/content/drive/MyDrive/Hasil Algoritma/XGBoost'
os.makedirs(output_dir, exist_ok=True)

results_excel_path = os.path.join(output_dir, 'xgboost_results.xlsx')
classification_report_excel_path = os.path.join(output_dir, 'xgboost_classification_report.xlsx')
conf_matrix_excel_path = os.path.join(output_dir, 'confusion_matrix.xlsx')
category_accuracy_excel_path = os.path.join(output_dir, 'category_accuracy.xlsx')
metrics_excel_path = os.path.join(output_dir, 'tp_fp_fn_tn.xlsx')

# Simpan hasil prediksi dan evaluasi
results_df = pd.DataFrame({"Actual": y_test.reset_index(drop=True), "Predicted": y_pred_xgb})
results_df.to_excel(results_excel_path, index=False)

# Simpan classification report ke Excel
classification_report_df = pd.DataFrame(classification_report_dict).transpose()
classification_report_df.to_excel(classification_report_excel_path, index=True)

# Simpan confusion matrix ke Excel
conf_matrix_df = pd.DataFrame(conf_matrix, index=target_names, columns=target_names)
conf_matrix_df.to_excel(conf_matrix_excel_path)

# Simpan akurasi per kategori ke Excel
category_accuracy_df.to_excel(category_accuracy_excel_path, index=False)

# Simpan TP, FP, FN, TN ke Excel
metrics_df.to_excel(metrics_excel_path, index=False)

# Cetak informasi path penyimpanan
print(f"\nHasil prediksi XGBoost telah disimpan di: {results_excel_path}")
print(f"Classification report telah disimpan di: {classification_report_excel_path}")
print(f"Confusion Matrix telah disimpan di: {conf_matrix_excel_path}")
print(f"Accuracy per Category telah disimpan di: {category_accuracy_excel_path}")
print(f"TP, FP, FN, TN per Category telah disimpan di: {metrics_excel_path}")



Confusion Matrix:
[[ 7  0  0  0  1  0  0  2  0  0  1  0]
 [ 0 11  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 11  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  7  0  0  0  2  0  0]
 [ 0  0  0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 12  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 11  0  0  0]
 [ 0  0  0  0  0  1  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  9]]

TP, FP, FN, TN per Category:
+----+----------+--------------------+---------------------+---------------------+--------------------+
|    | Category | True Positive (TP) | False Positive (FP) | False Negative (FN) | True Negative (TN) |
+----+----------+--------------------+---------------------+---------------------+--------------------+
| 0  |    0     |         7          |          0          |          4          |        120         |
| 1  |    1     |         11         |          0          |      

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv1D, MaxPooling1D, Flatten
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Membentuk ulang data untuk CNN
X_train_cnn = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test_cnn = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

# Mengidentifikasi jumlah kelas
num_classes = len(label_encoder.classes_)

# Membuat model CNN
cnn_model = Sequential()
cnn_model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(X_train_cnn.shape[1], 1)))
cnn_model.add(MaxPooling1D(pool_size=2))
cnn_model.add(Flatten())
cnn_model.add(Dense(100, activation='relu'))
cnn_model.add(Dropout(0.5))
cnn_model.add(Dense(num_classes, activation='softmax'))  # Menggunakan num_classes sebagai jumlah unit di layer output

# Kompilasi model
cnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Melatih model
cnn_model.fit(X_train_cnn, y_train, epochs=10, batch_size=32, validation_split=0.2)

# Memprediksi dan mengevaluasi model
y_pred_proba = cnn_model.predict(X_test_cnn)  # Menghasilkan probabilitas untuk setiap kelas
y_pred_cnn = y_pred_proba.argmax(axis=1)  # Mengambil kelas dengan probabilitas tertinggi

# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred_cnn)
accuracy_percentage = accuracy * 100
print(f"Accuracy: {accuracy_percentage:.2f}%")

# Menyimpan hasil ke Excel dan file teks
results_excel_path = '/content/drive/MyDrive/Hasil Algoritma/CNN/cnn_results.xlsx'
classification_report_path = '/content/drive/MyDrive/Hasil Algoritma/CNN/cnn_classification_report.txt'
conf_matrix_excel_path = '/content/drive/MyDrive/Hasil Algoritma/CNN/cnn_confusion_matrix.xlsx'

# Simpan hasil prediksi dan evaluasi
results_df = pd.DataFrame({"Actual": y_test.reset_index(drop=True), "Predicted": y_pred_cnn})
results_df.to_excel(results_excel_path, index=False)

# Simpan confusion matrix ke Excel
conf_matrix = confusion_matrix(y_test, y_pred_cnn)
conf_matrix_df = pd.DataFrame(conf_matrix, index=label_encoder.classes_, columns=label_encoder.classes_)
conf_matrix_df.to_excel(conf_matrix_excel_path)

# Simpan classification report ke file teks
classification_report_str = classification_report(y_test, y_pred_cnn)
with open(classification_report_path, 'w') as f:
    f.write(classification_report_str)

# Cetak informasi path penyimpanan
print(f"\nHasil prediksi CNN telah disimpan di: {results_excel_path}")
print(f"Classification report telah disimpan di: {classification_report_path}")
print(f"Confusion Matrix telah disimpan di: {conf_matrix_excel_path}")


Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.2197 - loss: 2.3101 - val_accuracy: 0.5410 - val_loss: 1.6965
Epoch 2/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6013 - loss: 1.5042 - val_accuracy: 0.5574 - val_loss: 1.2383
Epoch 3/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7183 - loss: 1.0680 - val_accuracy: 0.6885 - val_loss: 1.0133
Epoch 4/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7170 - loss: 0.8256 - val_accuracy: 0.7213 - val_loss: 0.8917
Epoch 5/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7959 - loss: 0.6636 - val_accuracy: 0.7541 - val_loss: 0.8169
Epoch 6/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7642 - loss: 0.7008 - val_accuracy: 0.7869 - val_loss: 0.7773
Epoch 7/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8187 - loss: 0.5299 - val_accuracy: 0.7869 - val_loss: 0.7057
Epoch 8/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7991 - loss: 0.4635 - val_accuracy: 0.8197 - val_loss: 0.6699
Epoch 9/10


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from tabulate import tabulate

# Memprediksi dan mengevaluasi model CNN
y_pred_cnn = cnn_model.predict(X_test_cnn)
y_pred_cnn_classes = y_pred_cnn.argmax(axis=1)

# Menghitung akurasi keseluruhan
accuracy = accuracy_score(y_test, y_pred_cnn_classes)
accuracy_percentage = accuracy * 100

# Menampilkan akurasi dalam format persentase
print(f"CNN Accuracy: {accuracy_percentage:.2f}%")

# Menampilkan Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred_cnn_classes)
conf_matrix_df = pd.DataFrame(conf_matrix, index=target_names, columns=target_names)
print("\nConfusion Matrix:")
print(tabulate(conf_matrix_df, headers='keys', tablefmt='pretty'))

# Menghitung TP, FP, FN, TN untuk setiap kategori
tp = conf_matrix.diagonal()
fp = conf_matrix.sum(axis=0) - tp
fn = conf_matrix.sum(axis=1) - tp
tn = conf_matrix.sum() - (fp + fn + tp)

# Buat DataFrame untuk TP, FP, FN, TN
metrics_df = pd.DataFrame({
    'Category': target_names,
    'True Positive (TP)': tp,
    'False Positive (FP)': fp,
    'False Negative (FN)': fn,
    'True Negative (TN)': tn
})
print("\nTP, FP, FN, TN per Category:")
print(tabulate(metrics_df, headers='keys', tablefmt='pretty'))

# Mengubah target names menjadi string
target_names = [str(i) for i in sorted(set(y_test))]

# Classification report
classification_report_dict = classification_report(y_test, y_pred_cnn_classes, target_names=target_names, output_dict=True)
classification_report_df = pd.DataFrame(classification_report_dict).transpose()

# Tampilkan classification report
print("\nClassification Report:")
print(tabulate(classification_report_df, headers='keys', tablefmt='pretty'))

# Extract akurasi per kategori dari classification report
category_accuracy = {category: metrics['recall'] for category, metrics in classification_report_dict.items() if category != 'accuracy'}

# Tampilkan akurasi per kategori
category_accuracy_df = pd.DataFrame(list(category_accuracy.items()), columns=['Category', 'Accuracy'])
category_accuracy_df['Accuracy'] = (category_accuracy_df['Accuracy'] * 100).round(2)  # Convert to percentage and round to 2 decimal places
print("\nAccuracy per Category:")
print(tabulate(category_accuracy_df, headers='keys', tablefmt='pretty'))

# Menyimpan hasil ke Excel
category_accuracy_excel_path = '/content/drive/MyDrive/Hasil Algoritma/CNN/category_accuracy.xlsx'
conf_matrix_excel_path = '/content/drive/MyDrive/Hasil Algoritma/CNN/confusion_matrix.xlsx'
metrics_excel_path = '/content/drive/MyDrive/Hasil Algoritma/CNN/tp_fp_fn_tn.xlsx'
classification_report_excel_path = '/content/drive/MyDrive/Hasil Algoritma/CNN/classification_report.xlsx'

category_accuracy_df.to_excel(category_accuracy_excel_path, index=False)
conf_matrix_df.to_excel(conf_matrix_excel_path)
metrics_df.to_excel(metrics_excel_path, index=False)
classification_report_df.to_excel(classification_report_excel_path)

print(f"\nAccuracy per Category telah disimpan di: {category_accuracy_excel_path}")
print(f"Confusion Matrix telah disimpan di: {conf_matrix_excel_path}")
print(f"TP, FP, FN, TN per Category telah disimpan di: {metrics_excel_path}")
print(f"Classification Report telah disimpan di: {classification_report_excel_path}")


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 
CNN Accuracy: 82.44%

Confusion Matrix:
+----+---+---+----+----+---+---+----+----+----+----+----+----+
|    | 0 | 1 | 2  | 3  | 4 | 5 | 6  | 7  | 8  | 9  | 10 | 11 |
+----+---+---+----+----+---+---+----+----+----+----+----+----+
| 0  | 6 | 0 | 0  | 0  | 1 | 0 | 2  | 0  | 0  | 0  | 1  | 1  |
| 1  | 0 | 0 | 0  | 0  | 0 | 0 | 0  | 0  | 11 | 0  | 0  | 0  |
| 2  | 0 | 0 | 11 | 0  | 0 | 0 | 0  | 0  | 0  | 0  | 0  | 0  |
| 3  | 0 | 0 | 0  | 11 | 0 | 0 | 0  | 0  | 0  | 0  | 0  | 0  |
| 4  | 1 | 0 | 0  | 0  | 9 | 0 | 0  | 0  | 0  | 0  | 0  | 1  |
| 5  | 2 | 0 | 0  | 0  | 0 | 7 | 0  | 0  | 0  | 0  | 0  | 0  |
| 6  | 0 | 0 | 0  | 0  | 0 | 0 | 10 | 0  | 0  | 0  | 0  | 1  |
| 7  | 0 | 0 | 0  | 0  | 0 | 1 | 0  | 11 | 0  | 0  | 0  | 0  |
| 8  | 0 | 0 | 0  | 0  | 0 | 0 | 0  | 0  | 11 | 0  | 0  | 0  |
| 9  | 0 | 0 | 0  | 0  | 0 | 0 | 0  | 0  | 0  | 10 | 1  | 0  |
| 10 | 0 | 0 | 0  | 0  | 0 | 0 | 0  | 0  | 0  | 0  | 11 | 0  |
| 11 | 0 | 0 | 0  | 0  | 0 | 0 | 0  | 0 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report

# Menghitung akurasi keseluruhan untuk setiap model
accuracy_rf = accuracy_score(y_test, y_pred_rf)
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
accuracy_cnn = accuracy_score(y_test, y_pred_cnn_classes)

# Mengonversi akurasi menjadi persentase dan membatasi ke dua digit di belakang koma
accuracy_rf_percentage = round(accuracy_rf * 100, 2)
accuracy_xgb_percentage = round(accuracy_xgb * 100, 2)
accuracy_cnn_percentage = round(accuracy_cnn * 100, 2)

# Membuat DataFrame untuk menyimpan hasil keseluruhan
results = {
    "Model": ["Random Forest", "XGBoost", "CNN"],
    "Accuracy (%)": [
        accuracy_rf_percentage,
        accuracy_xgb_percentage,
        accuracy_cnn_percentage
    ]
}

results_df = pd.DataFrame(results)

# Menampilkan hasil akurasi keseluruhan
print("Overall Model Accuracy:")
print(results_df)

# Menghitung akurasi per kategori untuk setiap model
classification_report_rf = classification_report(y_test, y_pred_rf, output_dict=True)
classification_report_xgb = classification_report(y_test, y_pred_xgb, output_dict=True)
classification_report_cnn = classification_report(y_test, y_pred_cnn_classes, output_dict=True)

category_accuracy_rf = {category: metrics['recall'] for category, metrics in classification_report_rf.items() if category != 'accuracy'}
category_accuracy_xgb = {category: metrics['recall'] for category, metrics in classification_report_xgb.items() if category != 'accuracy'}
category_accuracy_cnn = {category: metrics['recall'] for category, metrics in classification_report_cnn.items() if category != 'accuracy'}

# Mengonversi akurasi per kategori menjadi persentase dan membatasi ke dua digit di belakang koma
category_accuracy_rf = {category: round(accuracy * 100, 2) for category, accuracy in category_accuracy_rf.items()}
category_accuracy_xgb = {category: round(accuracy * 100, 2) for category, accuracy in category_accuracy_xgb.items()}
category_accuracy_cnn = {category: round(accuracy * 100, 2) for category, accuracy in category_accuracy_cnn.items()}

# Membuat DataFrame untuk menyimpan hasil per kategori
category_results_df = pd.DataFrame({
    "Category": category_accuracy_rf.keys(),
    "Random Forest (%)": category_accuracy_rf.values(),
    "XGBoost (%)": category_accuracy_xgb.values(),
    "CNN (%)": category_accuracy_cnn.values()
})

# Menampilkan hasil akurasi per kategori
print("\nAccuracy per Category for Each Model:")
print(category_results_df)

# Menyimpan hasil ke Excel
overall_accuracy_excel_path = '/content/drive/MyDrive/Hasil Algoritma/overall_model_accuracy.xlsx'
category_accuracy_excel_path = '/content/drive/MyDrive/Hasil Algoritma/category_model_accuracy.xlsx'

results_df.to_excel(overall_accuracy_excel_path, index=False)
category_results_df.to_excel(category_accuracy_excel_path, index=False)

print(f"\nOverall Model Accuracy telah disimpan di: {overall_accuracy_excel_path}")
print(f"Accuracy per Category for Each Model telah disimpan di: {category_accuracy_excel_path}")


Overall Model Accuracy:
           Model  Accuracy (%)
0  Random Forest         91.60
1        XGBoost         92.37
2            CNN         82.44

Accuracy per Category for Each Model:
        Category  Random Forest (%)  XGBoost (%)  CNN (%)
0              0              72.73        63.64    54.55
1              1              90.91       100.00     0.00
2              2             100.00       100.00   100.00
3              3             100.00       100.00   100.00
4              4              90.91        90.91    81.82
5              5              77.78        77.78    77.78
6              6             100.00       100.00    90.91
7              7             100.00       100.00    91.67
8              8              81.82       100.00   100.00
9              9              90.91        90.91    90.91
10            10             100.00       100.00   100.00
11            11              90.91        81.82   100.00
12     macro avg              91.33        92.09    82.30
1

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
